errcontext,FUNC_0
plpython_inline_error_callback,FUNC_1
arg,VAR_0
